<?php
// module/Usuario/view/usuario/usuario/index.phtml:

$title = 'Usuarios';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('usuario', ['action' => 'add']) ?>">Adicionar novo usuario</a>
</p>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Senha</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($usuarios as $usuario) : ?>
    <tr>
        <td><?= $this->escapeHtml($usuario->nome) ?></td>
        <td><?= $this->escapeHtml($usuario->email) ?></td>
        <td><?= $this->escapeHtml($usuario->senha) ?></td>
        <td>
            <a href="<?= $this->url('usuario', ['action' => 'edit', 'id' => $usuario->id]) ?>">Edit</a>
            <a href="<?= $this->url('usuario', ['action' => 'delete', 'id' => $usuario->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>