<?php

$title = 'Usuários';
$this->headTitle($title);
$url   = $this->url('usuario', ['action' => 'index']);
?>
<div class="row align-items-center">
    <div class="col-6">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <p>
            <a href="<?= $this->url('usuario', ['action' => 'add']) ?>">Adicionar novo usuario</a>
        </p>
    </div>
    <div class="col-6 row">
        <form action="<?= $this->url('usuario', ['action' => 'index']) ?>" class="col-12 row" method="post">
            <input type="text" name="nome" class="col-10 form-control" placeholder="Informe o nome do usuário">
            <input type="submit" value="Buscar" class="col-2 btn btn-primary">
        </form>
    </div>
</div>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Senha</th>
    <th>Ação</th>
</tr>
<?php foreach ($usuarios as $usuario) : ?>
    <tr>
        <td><?= $this->escapeHtml($usuario->nome) ?></td>
        <td><?= $this->escapeHtml($usuario->email) ?></td>
        <td><?= $this->escapeHtml($usuario->senha) ?></td>
        <td>
            <a href="<?= $this->url('usuario', ['action' => 'edit', 'id' => $usuario->id]) ?>">Editar</a>
            <a href="<?= $this->url('usuario', ['action' => 'delete', 'id' => $usuario->id]) ?>">Deletar</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>